# Generated by Django 5.2.17 on 2026-08-19 13:58

import caretaker_assignments.models
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('animals', '0003_alter_animal_birth_date'),
        ('caretakers', '0003_alter_caretaker_dni_alter_caretaker_email_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='CaretakerAssignment',
            fields=[
                ('id', models.CharField(default=caretaker_assignments.models.generate_ulid, editable=False, max_length=26, primary_key=True, serialize=False)),
                ('status', models.CharField(choices=[('active', 'Activo'), ('finished', 'Terminado')], default='active', max_length=20)),
                ('assignment_at', models.DateTimeField(blank=True, null=True)),
                ('notes', models.CharField(blank=True, max_length=350, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('animal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='caretaker_assignments', to='animals.animal')),
                ('caretaker', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='caretaker_assignments', to='caretakers.caretaker')),
            ],
            options={
                'verbose_name': 'CaretakerAssignment',
                'verbose_name_plural': 'CaretakerAssignments',
                'ordering': ['-created_at'],
            },
        ),
    ]
