# Generated by Django 5.2.17 on 2026-08-17 22:35

import django.db.models.deletion
import django.utils.timezone
import vaccination_records.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('animals', '0002_alter_animal_options_alter_animal_species'),
    ]

    operations = [
        migrations.CreateModel(
            name='VaccinationRecord',
            fields=[
                ('id', models.CharField(default=vaccination_records.models.generate_ulid, editable=False, max_length=26, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=200)),
                ('status', models.CharField(choices=[('applied', 'Aplicado'), ('pending', 'Pendiente'), ('cancel', 'Cancelado')], default='pending', max_length=20)),
                ('applied_at', models.DateTimeField(blank=True, default=django.utils.timezone.now, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('animal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vaccination_records', to='animals.animal')),
            ],
            options={
                'verbose_name': 'VaccinationRecord',
                'verbose_name_plural': 'VaccinationRecords',
                'ordering': ['-created_at'],
            },
        ),
    ]
