# Generated by Django 5.2.17 on 2026-08-17 23:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vaccination_records', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vaccinationrecord',
            name='applied_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
