# Generated by Django 5.2.17 on 2026-08-16 13:20

import animals.models
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Animal',
            fields=[
                ('id', models.CharField(default=animals.models.generate_ulid, editable=False, max_length=26, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=150)),
                ('species', models.CharField(max_length=100)),
                ('sex', models.CharField(choices=[('male', 'Macho'), ('female', 'Hembra'), ('unknown', 'Desconocido')], max_length=10)),
                ('birth_date', models.DateTimeField(blank=True, default=django.utils.timezone.now, null=True)),
                ('admission_date', models.DateTimeField(blank=True, default=django.utils.timezone.now, null=True)),
                ('adoption_status', models.CharField(choices=[('available', 'Disponible'), ('reserved', 'Reservado'), ('adopted', 'Adoptado'), ('not_available', 'No disponible')], default='available', max_length=20)),
                ('medical_status', models.CharField(choices=[('healthy', 'Sano'), ('in_treatment', 'En tratamiento'), ('quarantine', 'Cuarentena'), ('critical', 'Crítico')], default='healthy', max_length=20)),
                ('description', models.TextField(blank=True, null=True)),
                ('photo', models.ImageField(blank=True, null=True, upload_to='animals/photos/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Animal',
                'verbose_name_plural': 'Animales',
                'ordering': ['-created_at'],
            },
        ),
    ]
