# Generated by Django 5.2.17 on 2026-08-18 13:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('animals', '0002_alter_animal_options_alter_animal_species'),
    ]

    operations = [
        migrations.AlterField(
            model_name='animal',
            name='birth_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
