# Generated by Django 5.2.17 on 2026-08-19 13:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('animals', '0003_alter_animal_birth_date'),
        ('caretaker_assignments', '0001_initial'),
        ('caretakers', '0003_alter_caretaker_dni_alter_caretaker_email_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='animal',
            name='caretakers',
            field=models.ManyToManyField(blank=True, related_name='animals', through='caretaker_assignments.CaretakerAssignment', to='caretakers.caretaker'),
        ),
    ]
