# Generated by Django 5.2.17 on 2026-08-18 17:37

import adoption_applications.models
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('adopters', '0005_alter_adopter_email_alter_adopter_phone'),
        ('animals', '0003_alter_animal_birth_date'),
    ]

    operations = [
        migrations.CreateModel(
            name='AdoptionApplication',
            fields=[
                ('id', models.CharField(default=adoption_applications.models.generate_ulid, editable=False, max_length=26, primary_key=True, serialize=False)),
                ('status', models.CharField(choices=[('submitted', 'Enviada'), ('revision', 'Revision'), ('rejected', 'Rechazada')], default='submitted', max_length=20)),
                ('submitted_at', models.DateTimeField(blank=True, null=True)),
                ('reviewed_at', models.DateTimeField(blank=True, null=True)),
                ('notes', models.CharField(blank=True, max_length=350, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('adopter', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='adoption_applications', to='adopters.adopter')),
                ('animal', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='adoption_applications', to='animals.animal')),
            ],
            options={
                'verbose_name': 'AdoptionApplication',
                'verbose_name_plural': 'AdoptionApplications',
                'ordering': ['-created_at'],
            },
        ),
    ]
