# Generated by Django 5.2.17 on 2026-08-19 12:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adoption_applications', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='adoptionapplication',
            name='status',
            field=models.CharField(choices=[('submitted', 'Enviada'), ('revision', 'Revision'), ('rejected', 'Rechazada'), ('closed', 'Cerrado')], default='submitted', max_length=20),
        ),
    ]
