# Generated by Django 5.2.17 on 2026-08-18 13:12

import django.db.models.deletion
import medical_treatments.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('animals', '0003_alter_animal_birth_date'),
        ('veterinarians', '0001_initial')
    ]

    operations = [
        migrations.CreateModel(
            name='MedicalTreatment',
            fields=[
                ('id', models.CharField(default=medical_treatments.models.generate_ulid, editable=False, max_length=26, primary_key=True, serialize=False)),
                ('diagnostic', models.CharField(max_length=100)),
                ('status', models.CharField(choices=[('pending', 'Pendiente'), ('started', 'Empezado'), ('finalized', 'Finalizado')], default='pending', max_length=20)),
                ('description', models.CharField(max_length=300)),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('ended_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('animal', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='medical_treatments', to='animals.animal')),
                ('veterinarian', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='medical_treatments', to='veterinarians.veterinarian')),
            ],
            options={
                'verbose_name': 'MedicalTreatment',
                'verbose_name_plural': 'MedicalTreatments',
                'ordering': ['-created_at'],
            },
        ),
    ]
