# Generated by Django 5.2.17 on 2026-08-19 15:07

import django.core.validators
import django.db.models.deletion
import donations.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('adopters', '0005_alter_adopter_email_alter_adopter_phone'),
    ]

    operations = [
        migrations.CreateModel(
            name='Donation',
            fields=[
                ('id', models.CharField(default=donations.models.generate_ulid, editable=False, max_length=26, primary_key=True, serialize=False)),
                ('mount', models.PositiveBigIntegerField(validators=[django.core.validators.MinValueValidator(1)])),
                ('type_donation', models.CharField(choices=[('cash', 'Efectivo'), ('transfer', 'Transferencia'), ('food', 'Comida'), ('other', 'Otros')], default='cash', max_length=20)),
                ('status', models.CharField(choices=[('accept', 'Aceptado'), ('rejected', 'Rechazada')], default='accept', max_length=20)),
                ('donated_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('adopter', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='donations', to='adopters.adopter')),
            ],
            options={
                'verbose_name': 'Donation',
                'verbose_name_plural': 'Donations',
                'ordering': ['-created_at'],
            },
        ),
    ]
