# Generated by Django 5.2.17 on 2026-08-17 21:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adopters', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='adopter',
            name='email',
            field=models.EmailField(blank=True, max_length=254, unique=True),
        ),
    ]
