# Generated by Django 5.2.17 on 2026-08-18 14:00

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adopters', '0002_alter_adopter_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='adopter',
            name='dni',
            field=models.PositiveBigIntegerField(unique=True, validators=[django.core.validators.MinValueValidator(1000000), django.core.validators.MaxValueValidator(99999999)]),
        ),
        migrations.AlterField(
            model_name='adopter',
            name='phone',
            field=models.PositiveBigIntegerField(unique=True, validators=[django.core.validators.MinValueValidator(100000)]),
        ),
    ]
