# Generated by Django 5.2.17 on 2026-08-18 14:01

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adopters', '0003_alter_adopter_dni_alter_adopter_phone'),
    ]

    operations = [
        migrations.AlterField(
            model_name='adopter',
            name='phone',
            field=models.PositiveBigIntegerField(blank=True, unique=True, validators=[django.core.validators.MinValueValidator(100000)]),
        ),
    ]
