# Generated by Django 5.2.17 on 2026-08-18 14:05

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adopters', '0004_alter_adopter_phone'),
    ]

    operations = [
        migrations.AlterField(
            model_name='adopter',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='adopter',
            name='phone',
            field=models.PositiveBigIntegerField(blank=True, null=True, unique=True, validators=[django.core.validators.MinValueValidator(100000)]),
        ),
    ]
