# Generated by Django 5.2.17 on 2026-08-19 12:37

import adoption_events.models
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('adopters', '0005_alter_adopter_email_alter_adopter_phone'),
        ('adoption_applications', '0002_alter_adoptionapplication_status'),
        ('animals', '0003_alter_animal_birth_date'),
    ]

    operations = [
        migrations.CreateModel(
            name='AdoptionEvent',
            fields=[
                ('id', models.CharField(default=adoption_events.models.generate_ulid, editable=False, max_length=26, primary_key=True, serialize=False)),
                ('status', models.CharField(choices=[('ongoing', 'En Curso'), ('rejected', 'Rechazada'), ('closed', 'Cerrado')], default='ongoing', max_length=20)),
                ('adopted_at', models.DateTimeField(blank=True, null=True)),
                ('notes', models.CharField(blank=True, max_length=350, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('adopter', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='adoption_event', to='adopters.adopter')),
                ('adoption_application', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='adoption_event', to='adoption_applications.adoptionapplication', unique=True)),
                ('animal', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='adoption_event', to='animals.animal')),
            ],
            options={
                'verbose_name': 'AdoptionEvent',
                'verbose_name_plural': 'AdoptionEvents',
                'ordering': ['-created_at'],
            },
        ),
    ]
