# Generated by Django 5.2.17 on 2026-08-19 13:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adopters', '0005_alter_adopter_email_alter_adopter_phone'),
        ('adoption_applications', '0002_alter_adoptionapplication_status'),
        ('adoption_events', '0001_initial'),
        ('animals', '0003_alter_animal_birth_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='adoptionevent',
            name='adopter',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='adoption_events', to='adopters.adopter'),
        ),
        migrations.AlterField(
            model_name='adoptionevent',
            name='adoption_application',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='adoption_events', to='adoption_applications.adoptionapplication', unique=True),
        ),
        migrations.AlterField(
            model_name='adoptionevent',
            name='animal',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='adoption_events', to='animals.animal'),
        ),
    ]
