# Generated by Django 5.2.17 on 2026-08-18 14:44

import django.core.validators
import veterinarians.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Veterinarian',
            fields=[
                ('id', models.CharField(default=veterinarians.models.generate_ulid, editable=False, max_length=26, primary_key=True, serialize=False)),
                ('full_name', models.CharField(max_length=200)),
                ('dni', models.PositiveBigIntegerField(unique=True, validators=[django.core.validators.MinValueValidator(1000000), django.core.validators.MaxValueValidator(99999999)])),
                ('email', models.EmailField(blank=True, max_length=254, null=True, unique=True)),
                ('phone', models.PositiveBigIntegerField(blank=True, null=True, unique=True, validators=[django.core.validators.MinValueValidator(100000)])),
                ('status', models.CharField(choices=[('active', 'Activo'), ('blocked', 'Bloqueado')], default='active', max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Veterinarian',
                'verbose_name_plural': 'Veterinarians',
                'ordering': ['-created_at'],
            },
        ),
    ]
