# Generated by Django 5.2.17 on 2026-08-17 21:26

import veterinarians.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Veterinatian',
            fields=[
                ('id', models.CharField(default=veterinarians.models.generate_ulid, editable=False, max_length=26, primary_key=True, serialize=False)),
                ('full_name', models.CharField(max_length=200)),
                ('dni', models.CharField(max_length=20, unique=True)),
                ('email', models.EmailField(blank=True, max_length=254, unique=True)),
                ('phone', models.CharField(blank=True, max_length=30)),
                ('status', models.CharField(choices=[('active', 'Activo'), ('blocked', 'Bloqueado')], default='active', max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Veterinatian',
                'verbose_name_plural': 'Veterinarians',
                'ordering': ['-created_at'],
            },
        ),
    ]
