# Generated by Django 5.2.17 on 2026-08-17 21:31

import caretakers.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('caretakers', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='caretaker',
            name='email',
            field=models.EmailField(blank=True, max_length=254, unique=True),
        ),
        migrations.AlterField(
            model_name='caretaker',
            name='id',
            field=models.CharField(default=caretakers.models.generate_ulid, editable=False, max_length=26, primary_key=True, serialize=False),
        ),
    ]
