# Generated by Django 5.2.17 on 2026-08-18 14:10

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('caretakers', '0002_alter_caretaker_email_alter_caretaker_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='caretaker',
            name='dni',
            field=models.PositiveBigIntegerField(unique=True, validators=[django.core.validators.MinValueValidator(1000000), django.core.validators.MaxValueValidator(99999999)]),
        ),
        migrations.AlterField(
            model_name='caretaker',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='caretaker',
            name='phone',
            field=models.PositiveBigIntegerField(blank=True, null=True, unique=True, validators=[django.core.validators.MinValueValidator(100000)]),
        ),
    ]
